# Generated by Django 2.2.10 on 2021-02-09 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pricing_page_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_page',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pricing'),
        ),
    ]
