# Generated by Django 2.2.10 on 2021-02-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210209_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing_page',
            name='pricing',
        ),
    ]
