# Generated by Django 2.2.10 on 2021-02-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_pricing_page_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_page',
            name='page_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
